In [1]:
import sqlite3

In [2]:
import pandas as pd

In [3]:
conn=sqlite3.connect('test.db')

In [9]:
conn.execute(
'''
CREATE TABLE IF NOT EXISTS students(
id INTEGER,
    name TEXT,
    age INTERGER,
    score INTEGER
    )
    
''')

In [13]:
conn.execute("INSERT INTO.students VALUES (1, 'A', 23, 88)")

OperationalError: near ".": syntax error

In [15]:
conn.execute("INSERT INTO students VALUES (1, 'A', 23, 88)")

In [16]:
conn.execute("INSERT INTO students VALUES (2, 'B', 44, 99)")

In [17]:
conn.execute("INSERT INTO students VALUES (3, 'C', 55, 77)")

In [18]:
conn.execute("INSERT INTO students VALUES (4, 'D', 66, 55)")

In [25]:
pd.read_sql('SELECT * FROM students',conn)

   id name  age  score
0   1    A   23     88
1   2    B   44     99
2   3    C   55     77
3   4    D   66     55

In [26]:
pd.read_sql('SELECT name, score FROM students', conn)

  name  score
0    A     88
1    B     99
2    C     77
3    D     55

In [42]:
result=pd.read_sql('SELECT * FROM students ORDER BY score DESC', conn)
print(result)
print("行数",len(result))

Empty DataFrame
Columns: [id, name, age, score]
Index: []
行数 0

In [35]:
pd.read_sql('SELECT * FROM students ORDER BY score', conn)

Empty DataFrame
Columns: [id, name, age, score]
Index: []

In [37]:
pd.read_sql('SELECT * FROM students WHERE score > 90', conn)

Empty DataFrame
Columns: [id, name, age, score]
Index: []

In [43]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)

       name
0  students

In [44]:
conn.execute("DELETE FROM students")  # 清空，避免重复

conn.execute("INSERT INTO students VALUES (1, 'A', 23, 88)")
conn.execute("INSERT INTO students VALUES (2, 'B', 25, 99)")
conn.execute("INSERT INTO students VALUES (3, 'C', 22, 77)")
conn.execute("INSERT INTO students VALUES (4, 'D', 28, 55)")
conn.commit()

In [45]:
print(conn.commit())

None

In [46]:
pd.read_sql('SELECT * FROM students', conn)

   id name  age  score
0   1    A   23     88
1   2    B   25     99
2   3    C   22     77
3   4    D   28     55

In [47]:
df.to_sql('students', conn, if_exists='replace', index=False)

NameError: name 'df' is not defined

In [49]:
pd.read_sql('SELECT name, score FROM students', conn)

  name  score
0    A     88
1    B     99
2    C     77
3    D     55

In [50]:
pd.read_sql('SELECT * FROM students WHERE score>85', conn)

   id name  age  score
0   1    A   23     88
1   2    B   25     99

In [51]:
pd.read_sql('SELECT * FROM students ORDER BY  score DESC', conn)

   id name  age  score
0   2    B   25     99
1   1    A   23     88
2   3    C   22     77
3   4    D   28     55